Task 1

diff --git a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
--- a/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
+++ b/0x12-web_stack_debugging_2/1-run_nginx_as_nginx
@@ -1,17 +1,33 @@
 #!/usr/bin/env bash
-# Configuring Nginx
+# Configurations to run Nginx as the nginx user listening on port 8080.
 
-# Ensure that the nginx user exists
-if ! id -u nginx > /dev/null 2>&1; then
-	echo "User nginx doesn't exist.  Creating it..."
-	useradd -r nginx
+set -e
+
+# Update Nginx user to nginx
+if ! sed -Ei 's/\s*user .*/user nginx;/' /etc/nginx/nginx.conf; then
+	echo "Failed to update user in /etc/nginx/nginx.conf"
+	exit 1
 fi
 
-# Ensure that nginx is running
-sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
+# Update the port to 8080
+if ! sed -i 's/80/8080/g' /etc/nginx/sites-available/default; then
+	echo "Failed to update port in /etc/nginx/sites-available/default"
+	exit 1
+fi
 
-# Configure Nginx tolisten on port 8080
-sed -i 's/^.*listen\s\+80;/	listen 8080;/' /etc/nginx/sites-available/default
+# Change Permission of the nginx configuration file
+chmod 644 /etc/nginx/nginx.conf
 
-# Restart Nginx
-service nginx restart
+# Stop apache2
+service apache2 stop
+
+# Kill apache2 if running
+pkill apache2 || true
+
+# Restart Nginx as nginx user
+if ! sudo -u nginx service nginx restart; then
+	echo "Failed to restart Nginx"
+	exit 1
+fi
+
+echo "Nginx is now running as nginx user and listening on port 8080."
